python run.py parametersGenetic.json --ngen 20 --mu 5 --lambda 10 --newpb 0.5 --cxpb 0.5 --mutpb 0.5 --parallel
python run.py parametersGenetic.json --ngen 20 --mu 5 --lambda 10 --newpb 0.5 --cxpb 0.5 --mutpb 0.5 --parallel
python run.py parametersGenetic.json --ngen 20 --mu 5 --lambda 10 --newpb 0.5 --cxpb 0.5 --mutpb 0.5 --parallel
python run.py parametersGenetic.json --ngen 20 --mu 5 --lambda 10 --newpb 0.5 --cxpb 0.5 --mutpb 0.5 --parallel
python run.py parametersGenetic.json --ngen 20 --mu 5 --lambda 10 --newpb 0.5 --cxpb 0.5 --mutpb 0.5 --parallel
python run.py parametersGenetic.json --ngen 20 --mu 5 --lambda 10 --newpb 0.5 --cxpb 0.5 --mutpb 0.5 --parallel
python run.py parametersGenetic.json --ngen 20 --mu 5 --lambda 10 --newpb 0.5 --cxpb 0.5 --mutpb 0.5 --parallel
python run.py parametersGenetic.json --ngen 20 --mu 5 --lambda 10 --newpb 0.5 --cxpb 0.5 --mutpb 0.5 --parallel
python run.py parametersGenetic.json --ngen 20 --mu 5 --lambda 10 --newpb 0.5 --cxpb 0.5 --mutpb 0.5 --parallel
python run.py parametersGenetic.json --ngen 20 --mu 5 --lambda 10 --newpb 0.5 --cxpb 0.5 --mutpb 0.5 --parallel
python run.py parametersGenetic.json --ngen 20 --mu 5 --lambda 10 --newpb 0.5 --cxpb 0.5 --mutpb 0.5 --parallel
python run.py parametersGenetic.json --ngen 20 --mu 5 --lambda 10 --newpb 0.5 --cxpb 0.5 --mutpb 0.5 --parallel
python run.py parametersGenetic.json --ngen 20 --mu 5 --lambda 10 --newpb 0.5 --cxpb 0.5 --mutpb 0.5 --parallel
python run.py parametersGenetic.json --ngen 20 --mu 5 --lambda 10 --newpb 0.5 --cxpb 0.5 --mutpb 0.5 --parallel
python run.py parametersGenetic.json --ngen 20 --mu 5 --lambda 10 --newpb 0.5 --cxpb 0.5 --mutpb 0.5 --parallel
python run.py parametersGenetic.json --ngen 20 --mu 5 --lambda 10 --newpb 0.5 --cxpb 0.5 --mutpb 0.5 --parallel
python run.py parametersGenetic.json --ngen 20 --mu 5 --lambda 10 --newpb 0.5 --cxpb 0.5 --mutpb 0.5 --parallel
python run.py parametersGenetic.json --ngen 20 --mu 5 --lambda 10 --newpb 0.5 --cxpb 0.5 --mutpb 0.5 --parallel
python run.py parametersGenetic.json --ngen 20 --mu 5 --lambda 10 --newpb 0.5 --cxpb 0.5 --mutpb 0.5 --parallel
python run.py parametersGenetic.json --ngen 20 --mu 5 --lambda 10 --newpb 0.5 --cxpb 0.5 --mutpb 0.5 --parallel
